# Generated by Django 2.2.6 on 2019-10-17 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Passengers',
            fields=[
                ('passenger_id', models.AutoField(db_column='PASSENGER_ID', primary_key=True, serialize=False)),
                ('passenger_name', models.CharField(blank=True, db_column='PASSENGER_NAME', max_length=100, null=True)),
                ('age', models.IntegerField(blank=True, db_column='AGE', null=True)),
                ('phone_number', models.BigIntegerField(blank=True, db_column='PHONE_NUMBER', null=True)),
            ],
            options={
                'db_table': 'PASSENGERS',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Pnr',
            fields=[
                ('pnr_number', models.AutoField(db_column='PNR_NUMBER', primary_key=True, serialize=False)),
                ('train_id', models.IntegerField(blank=True, db_column='TRAIN_ID', null=True)),
                ('status', models.CharField(blank=True, db_column='STATUS', max_length=200, null=True)),
                ('seat_number', models.CharField(blank=True, db_column='SEAT_NUMBER', max_length=10, null=True)),
                ('user_id', models.CharField(blank=True, db_column='USER_ID', max_length=20, null=True)),
                ('passenger_id', models.IntegerField(blank=True, db_column='PASSENGER_ID', null=True)),
                ('boarding_point', models.IntegerField(blank=True, db_column='BOARDING_POINT', null=True)),
                ('boarding_time', models.TimeField(blank=True, db_column='BOARDING_TIME', null=True)),
                ('destination', models.IntegerField(blank=True, db_column='DESTINATION', null=True)),
                ('date_of_journey', models.DateField(blank=True, db_column='DATE_OF_JOURNEY', null=True)),
                ('ticket', models.FileField(db_column='TICKET', upload_to='tickets/')),
            ],
            options={
                'db_table': 'PNR',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Routes',
            fields=[
                ('route_id', models.AutoField(db_column='ROUTE_ID', primary_key=True, serialize=False)),
                ('train_id', models.IntegerField(blank=True, db_column='TRAIN_ID', null=True)),
                ('station_id', models.IntegerField(blank=True, db_column='STATION_ID', null=True)),
                ('arrival_time', models.TimeField(blank=True, db_column='ARRIVAL_TIME', null=True)),
                ('departure_time', models.TimeField(blank=True, db_column='DEPARTURE_TIME', null=True)),
            ],
            options={
                'db_table': 'ROUTES',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Stations',
            fields=[
                ('station_id', models.AutoField(db_column='STATION_ID', primary_key=True, serialize=False)),
                ('station_name', models.CharField(blank=True, db_column='STATION_NAME', max_length=100, null=True)),
                ('x', models.IntegerField(blank=True, db_column='X', null=True)),
                ('y', models.IntegerField(blank=True, db_column='Y', null=True)),
            ],
            options={
                'db_table': 'STATIONS',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Trains',
            fields=[
                ('train_id', models.AutoField(db_column='TRAIN_ID', primary_key=True, serialize=False)),
                ('train_name', models.CharField(blank=True, db_column='TRAIN_NAME', max_length=50, null=True)),
                ('origin', models.CharField(blank=True, db_column='ORIGIN', max_length=100, null=True)),
                ('end_point', models.CharField(blank=True, db_column='END_POINT', max_length=100, null=True)),
                ('departure_time', models.TimeField(blank=True, db_column='DEPARTURE_TIME', null=True)),
                ('max_capacity', models.IntegerField(blank=True, db_column='MAX_CAPACITY', null=True)),
                ('railway_classes', models.CharField(blank=True, db_column='RAILWAY_CLASSES', max_length=200, null=True)),
            ],
            options={
                'db_table': 'TRAINS',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.CharField(blank=True, db_column='USER_ID', max_length=20, primary_key=True, serialize=False)),
                ('user_name', models.CharField(db_column='USER_NAME', max_length=100)),
                ('password', models.CharField(db_column='PASSWORD', max_length=20)),
            ],
            options={
                'db_table': 'USERS',
                'managed': True,
            },
        ),
    ]
