# Generated by Django 2.2.6 on 2019-10-27 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='metadata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pnr', models.IntegerField(blank=True, db_column='pnr', null=True)),
                ('passengername', models.IntegerField(blank=True, db_column='passengername', null=True)),
                ('email', models.CharField(blank=True, db_column='email', max_length=150, null=True)),
                ('traveldate', models.DateField(blank=True, db_column='traveldate', null=True)),
                ('train1', models.IntegerField(blank=True, db_column='train1', null=True)),
                ('train2', models.IntegerField(blank=True, db_column='train2', null=True)),
                ('rclass', models.CharField(blank=True, db_column='rclass', max_length=150, null=True)),
                ('j', models.IntegerField(blank=True, db_column='j', null=True)),
                ('seatno', models.IntegerField(blank=True, db_column='seatno', null=True)),
                ('platformno', models.IntegerField(blank=True, db_column='platformno', null=True)),
                ('fromid', models.IntegerField(blank=True, db_column='fromid', null=True)),
                ('toid', models.IntegerField(blank=True, db_column='toid', null=True)),
                ('arrival', models.DateField(blank=True, db_column='arrival', null='True')),
                ('departure', models.DateField(blank=True, db_column='departure', null='True')),
            ],
            options={
                'db_table': 'mdata',
                'managed': True,
            },
        ),
    ]
