# Generated by Django 2.2.6 on 2019-10-27 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0002_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='trains',
            name='cf',
            field=models.IntegerField(db_column='CF', null=True),
        ),
    ]
