# Generated by Django 2.2.6 on 2019-10-27 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0003_trains_cf'),
    ]

    operations = [
        migrations.AddField(
            model_name='metadata',
            name='identifier',
            field=models.CharField(db_column='identifier', max_length=100, null=True),
        ),
    ]
