# Generated by Django 2.2.6 on 2019-11-11 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0005_auto_20191028_0045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pnr',
            name='boarding_point',
        ),
        migrations.RemoveField(
            model_name='pnr',
            name='boarding_time',
        ),
        migrations.RemoveField(
            model_name='pnr',
            name='date_of_journey',
        ),
        migrations.RemoveField(
            model_name='pnr',
            name='destination',
        ),
        migrations.RemoveField(
            model_name='pnr',
            name='train_id',
        ),
        migrations.AddField(
            model_name='passengers',
            name='email',
            field=models.EmailField(max_length=250, null=True, unique=True, verbose_name='email'),
        ),
        migrations.AddField(
            model_name='pnr',
            name='arrival_time',
            field=models.TimeField(blank=True, db_column='ARRIVAL_TIME', null=True),
        ),
        migrations.AddField(
            model_name='pnr',
            name='booking_number',
            field=models.IntegerField(blank=True, db_column='booking-number', default=None, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pnr',
            name='dateofbooking',
            field=models.DateField(blank=True, db_column='dateofbooking', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pnr',
            name='dateofjourney',
            field=models.DateField(blank=True, db_column='dateofjourney', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pnr',
            name='departure_time',
            field=models.TimeField(blank=True, db_column='DEPARTURE_TIME', null=True),
        ),
        migrations.AddField(
            model_name='pnr',
            name='fromcity',
            field=models.CharField(blank=True, db_column='fromcity', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pnr',
            name='junction',
            field=models.IntegerField(blank=True, db_column='JUNCTION_ID', null=True),
        ),
        migrations.AddField(
            model_name='pnr',
            name='rclass',
            field=models.CharField(blank=True, db_column='rclass', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='pnr',
            name='tocity',
            field=models.CharField(blank=True, db_column='tocity', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pnr',
            name='train1_id',
            field=models.IntegerField(blank=True, db_column='TRAIN1_ID', null=True),
        ),
        migrations.AddField(
            model_name='pnr',
            name='train2_id',
            field=models.IntegerField(blank=True, db_column='TRAIN2_ID', null=True),
        ),
        migrations.AddField(
            model_name='pnr',
            name='typeofjourney',
            field=models.CharField(blank=True, db_column='typeofjourney', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='pnr',
            name='ticket',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to=''),
        ),
    ]
