# Generated by Django 2.2.6 on 2019-11-18 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0006_auto_20191111_1303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pnr',
            name='ticket',
        ),
    ]
