# Generated by Django 2.2.6 on 2019-11-21 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0007_remove_pnr_ticket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pnr',
            name='user_id',
        ),
        migrations.AddField(
            model_name='passengers',
            name='gender',
            field=models.CharField(blank=True, db_column='GENDER', max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='pnr',
            name='user_name',
            field=models.CharField(blank=True, db_column='USER_NAME', max_length=20, null=True),
        ),
    ]
