# Generated by Django 2.2.6 on 2019-11-21 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0008_auto_20191121_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pnr',
            name='booking_number',
            field=models.IntegerField(blank=True, db_column='booking_number', unique=True),
        ),
    ]
