# Generated by Django 2.2.6 on 2019-11-21 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0009_auto_20191121_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pnr',
            name='pnr_number',
            field=models.IntegerField(blank=True, db_column='PNR_NUMBER', primary_key=True, serialize=False),
        ),
    ]
