# Generated by Django 2.2.6 on 2019-11-21 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0010_auto_20191121_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pnr',
            name='pnr_number',
            field=models.CharField(blank=True, db_column='PNR_NUMBER', max_length=15, primary_key=True, serialize=False),
        ),
    ]
