# Generated by Django 2.2.6 on 2019-11-21 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0011_auto_20191121_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passengers',
            name='passenger_id',
            field=models.IntegerField(blank=True, db_column='PASSENGER_ID', primary_key=True, serialize=False),
        ),
    ]
