# Generated by Django 2.2.6 on 2019-11-27 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0013_auto_20191121_2148'),
    ]

    operations = [
        migrations.AddField(
            model_name='pnr',
            name='pnr_number2',
            field=models.CharField(blank=True, db_column='PNR_NUMBER2', max_length=15, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pnr',
            name='pnr_number',
            field=models.CharField(blank=True, db_column='PNR_NUMBER', max_length=15, null=True),
        ),
    ]
