# Generated by Django 2.2.6 on 2019-11-27 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0014_auto_20191127_1349'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pnr',
            name='pnr_number2',
        ),
        migrations.AlterField(
            model_name='pnr',
            name='booking_number',
            field=models.IntegerField(blank=True, db_column='booking_number', primary_key=True, serialize=False, unique=True),
        ),
    ]
